### ISSUE TITLE
Tabelle zum speichern von Benutzern

### ISSUE THREAD

**Issue by siebl** [soed2020-teamorange/ch.bfh.bti7081.s2020.orange#20]
# Beschreibung
Es existiert eine Tabelle in der Datenbank zum Abspeichern von Benutzern, deren Kontaktinformationen und Logindaten.

# Aufwand

Geschätzter: 2h

Aktuell:

Aktualisierter:

# Sub Tasks

**Comment by faebuk** [comment]
Wurde durch https://github.com/soed2020-teamorange/ch.bfh.bti7081.s2020.orange/pull/35 implementiert.
