### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by siebl** [soed2020-teamorange/ch.bfh.bti7081.s2020.orange#27]
# Beschreibung
Ein Benutzer kann sich im System übe eine Login-Page einloggen.

# Aufwand

Geschätzter Aufwand: 3h

Aktueller Aufwand:

Aktualisierter Aufwand:

# Sub Tasks

**Comment by faebuk** [comment]
Wurde mit https://github.com/soed2020-teamorange/ch.bfh.bti7081.s2020.orange/pull/35 implementiert.
