### ISSUE TITLE
Übersichtsseite für Notfallnummern

### ISSUE THREAD

**Issue by adberger** [soed2020-teamorange/ch.bfh.bti7081.s2020.orange#46]
# Beschreibung
Es soll eine Übersichtsseite erstellt werden auf welchen sich diverse Notfallnummern (Ambulanz, Therapeut etc.) befinden.
Gegebenenfalls auch auf der Startseite.

# Aufwand

Geschätzter Aufwand: 2h

Aktueller Aufwand:

Aktualisierter Aufwand:

**Comment by faebuk** [comment]
Wurde mit #60 geschlossen
