### ISSUE TITLE
UI für Stimmungstagebuch (Neuer Eintrag)

### ISSUE THREAD

**Issue by herzogj** [soed2020-teamorange/ch.bfh.bti7081.s2020.orange#54]
# Beschreibung
Ein Patient kann einen neuen Eintrag in sein Stimmungstagebuch erfassen.

AK1: DB-Entities für MoodDiary sind erstellt.
AK2: Ein Patient kann einen neuen Eintrag im Stimmungstagebuch erfassen. Dies beinhaltet einen Titel, ein Datum, eine Zeit, eine Stimmung, eine Beschreibung und ein Bild.

# Aufwand

Geschätzter Aufwand: 5h

Aktueller Aufwand:

Aktualisierter Aufwand:

**Comment by faebuk** [comment]
Wurde mit PR #61 fertiggestellt.
